char: phytnet_led: Convert to platform remove callback returning void
0edb555a6: platform: Make platform_driver::remove() return void
cause build error, so convert .remove from int to void

Log:
drivers/char/phytnetled/phytnet_led.c:314:19: error: initialization of ‘void (*)(struct platform_device *)’ from incompatible pointer type ‘int (*)(struct platform_device *)’ [-Werror=incompatible-pointer-types]
  314 |         .remove = net_led_remove,
      |                   ^~~~~~~~~~~~~~
drivers/char/phytnetled/phytnet_led.c:314:19: note: (near initialization for ‘net_led_driver.<anonymous>.remove’)
cc1: all warnings being treated as errors